---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: network
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: lanquarden@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudflare:
          email: lanquarden@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-key
            key: api-key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: network
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lanquarden@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        cloudflare:
          email: lanquarden@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-key
            key: api-key
