---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: frigate-rtmp-route
  namespace: home
spec:
  entryPoints:
    - rtmp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: frigate
          port: 1935
          weight: 10
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: snapcast-clients-route
  namespace: media
spec:
  entryPoints:
    - snapclients
  routes:
    - match: HostSNI(`snapcast.k.lanquarden.com`)
      services:
        - name: snapcast
          port: 1704
          weight: 10
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: snapcast-control-route
  namespace: media
spec:
  entryPoints:
    - snapcontrol
  routes:
    - match: HostSNI(`snapcast.k.lanquarden.com`)
      services:
        - name: snapcast
          port: 1705
          weight: 10
