---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: ghcr.io/n8n-io/n8n
      tag: 1.90.2
      imagePullPolicy: IfNotPresent

    env:
      TZ: 
      DB_SQLITE_VACUUM_ON_STARTUP: true
      EXECUTIONS_DATA_PRUNE: true
      EXECUTIONS_DATA_MAX_AGE: 7
      EXECUTIONS_DATA_PRUNE_MAX_COUNT: 50000
      GENERIC_TIMEZONE: "Europe/Madrid"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: false
      N8N_PROTOCOL: "https"
      N8N_PORT: &port 8080
      N8N_HOST: &hostName n8n.k.lanquarden.com
      N8N_LOG_LEVEL: info
      N8N_LOG_OUTPUT: console
      N8N_ENCRYPTION_KEY:
        valueFrom:
          secretKeyRef:
            name: n8n-secret
            key: N8N_ENCRYPTION_KEY

    service:
      main:
        ports:
          http:
            port: 8080.

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "n8n.k.lanquarden.com"
            paths:
              - path: /
        tls:
          - secretName: n8n-cert
            hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: n8n-data
        mountPath: /home/node/.n8n