---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: lidarr
      version: 10.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/lidarr
      tag: v1.0.0.2226
    env:
      TZ: "Europe/Madrid"
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: lidarr.k.lanquarden.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: lidarr-cert
            hosts:
              - "lidarr.k.lanquarden.com"
      api:
        enabled: true
        hosts:
          - host: lidarr.k.lanquarden.com
            paths:
              - path: /api
                pathType: Prefix
        tls:
          - hosts:
              - "lidarr.k.lanquarden.com"
    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config
      media:
        enabled: true
        mountPath: "/media"
        existingClaim: media-nfs-media-pvc
      unsorted:
        enabled: true
        mountPath: "/unsorted"
        existingClaim: media-nfs-unsorted-pvc
    podAnnotations:
      backup.velero.io/backup-volumes: config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
