---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://blakeblackshear.github.io/blakeshome-charts/
      chart: frigate
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: blakeshome-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: blakeblackshear/frigate
      tag: 0.9.4-amd64

    timezone: Europe/Madrid

    coral:
      enabled: false

    shmSize: 512Mi

    persistence:
      data:
        enabled: true
        existingClaim: frigate-data

    extraVolumes:
      - name: nfs-frigate
        persistentVolumeClaim:
          claimName: home-nfs-frigate-pvc
      - name: cache
        emptyDir:
          medium: Memory

    extraVolumeMounts:
      - name: nfs-frigate
        mountPath: /media/frigate
      - mountPath: /tmp/cache
        name: cache

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
        - frigate.k.lanquarden.com
      tls:
        - secretName: frigate-cert
          hosts:
            - frigate.k.lanquarden.com

    config: |
      mqtt:
        host: vernemq.home
        port: 1883
        topic_prefix: frigate
      database:
        path: /data/frigate.db
      detectors:
        cpu1:
          type: cpu
      objects:
        track:
          - person
          - dog
          - cat
      ffmpeg:
        hwaccel_args:
          - -hwaccel
          - qsv
          - -qsv_device
          - /dev/dri/renderD128
      cameras:
        doorbell:
          ffmpeg:
            inputs:
              - path: rtsp://{FRIGATE_DOORBELL_USER}:{FRIGATE_DOORBELL_PASS}@192.168.30.11:554/Streaming/Channels/102/
                roles:
                  - detect
              - path: rtsp://{FRIGATE_DOORBELL_USER}:{FRIGATE_DOORBELL_PASS}@192.168.30.11:554/Streaming/Channels/101/
                roles:
                  - record
                  - rtmp
          detect:
            width: 704
            height: 576
            fps: 12
          snapshots:
            enabled: True
            timestamp: True
            retain:
              # Required: Default retention days (default: shown below)
              default: 14
          objects:
            track:
              - person
    resources:
      requests:
        memory: 300Mi
        cpu: 400m
        gpu.intel.com/i915: 1
      limits:
        gpu.intel.com/i915: 1
        memory: 1000Mi
  valuesFrom:
    - kind: Secret
      name: "frigate-helm-values"
      optional: false
