---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.dexidp.io
      chart: dex
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: dex-charts
        namespace: flux-system
      interval: 10m
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 5
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: true
    recreate: true
  values:
    image:
      repository: docker.io/dexidp/dex
      tag: v2.28.1
    env:
      KUBERNETES_POD_NAMESPACE: network
    config:
      issuer: https://dex.k.lanquarden.com
      storage:
        type: kubernetes
        config:
          inCluster: true
      oauth2:
        alwaysShowLoginScreen: false
        responseTypes: ['code', 'token', 'id_token']
        skipApprovalScreen: true
      web:
        http: 0.0.0.0:5556
      frontend:
        theme: 'tecktonic'
        issuer: 'Lanquarden'
        issuerUrl: 'https://dex.k.lanquarden.com'
        logoURL: https://raw.githubusercontent.com/raspbernetes/docs/master/website/static/img/logo.png
      enablePasswordDB: false
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - dex.k.lanquarden.com
      tls:
        - secretName: dex-cert
          hosts:
            - dex.k.lanquarden.com
  valuesFrom:
    - kind: Secret
      name: "dex-helm-values"
