---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: routr
  namespace: communications
spec:
  interval: 5m
  chart:
    spec:
      chart: routr-connect
      version: 0.4.3
      sourceRef:
        kind: HelmRepository
        name: routr-charts
        namespace: flux-system

  values:
    global:
      logsLevel: debug
    edgePort:
      externalAddrs:
        - 192.168.1.24
      transport:
        tcp: 
          enabled: true
          port: 5060
        ws:
          enabled: true
          port: 5062


