---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-data
  namespace: home
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

  storageClassName: rook-ceph-block
