---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-nfs-frigate-pv
spec:
  storageClassName: home-nfs-frigate
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: storone.lanquarden.com
    path: /frigate
  mountOptions:
  - nfsvers=4.1
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-nfs-frigate-pvc
  namespace: home
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: home-nfs-frigate
  resources:
    requests:
      storage: 1Mi
