---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-db-data
  namespace: home
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 4Gi

  storageClassName: rook-ceph-block