---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wwebjs-data
  namespace: home
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi

  storageClassName: rook-ceph-block