---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: piper
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: rhasspy/wyoming-piper
      tag: 1.4.0
      imagePullPolicy: IfNotPresent

    args:
      - --voice=en_US-amy-medium

    resources:
      requests:
        cpu: 500m
      limits:
        cpu: 1000m

    service:
      main:
        ports:
          http:
            port: 10200

    persistence:
      data:
        enabled: true
        type: emptyDir
      tmp:
        enabled: true
        type: emptyDir
        medium: Memory