---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-db
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 4Gi

  storageClassName: rook-ceph-block
