---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-db
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 20Gi

  storageClassName: rook-ceph-block
