---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  targetNamespace: home
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.118.5
    extraEnv:
      TZ: "Europe/Madrid"
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.20
      additionalPorts:
        - name: homematic
          port: 2001
          targetPort: 2001
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
      - "hass.k.lanquarden.com"
      tls:
      - secretName: hass-cert
        hosts:
        - "hass.k.lanquarden.com"
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "rook-ceph-block"
    monitoring:
      enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
      limits:
        memory: 2500Mi
    influxdb:
      enabled: true
      architecture: standalone
      database: home_assistant
      authEnabled: false
      updateStrategy: Recreate
      persistence:
        enabled: true
        storageClass: "rook-ceph-block"
        size: 10Gi
      podAnnotations:
        backup.velero.io/backup-volumes: data
    vscode:
      enabled: true
      image:
        repository: codercom/code-server
        tag: 3.8.0
      extraEnv:
        HASS_SERVER: "http://localhost:8123"
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
        - "hass-editor.k.lanquarden.com"
        tls:
        - secretName: hass-editor-cert
          hosts:
          - "hass-editor.k.lanquarden.com"
