---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  targetNamespace: home
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 5.4.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: homeassistant/home-assistant
      tag: 2021.1.5
    extraEnv:
      TZ: "Europe/Madrid"
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.20
      additionalPorts:
        - name: homematic
          port: 2001
          targetPort: 2001
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: "hass.k.lanquarden.com"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: hass-editor-cert
          hosts:
            - "hass.k.lanquarden.com"
    persistence:
      config:
        enabled: true
        size: 10Gi
        storageClass: "rook-ceph-block"
    monitoring:
      enabled: false
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
      limits:
        memory: 2500Mi
    influxdb:
      enabled: true
      architecture: standalone
      database: home_assistant
      authEnabled: false
      updateStrategy: Recreate
      persistence:
        enabled: true
        storageClass: "rook-ceph-block"
        size: 10Gi
      podannotations:
        backup.velero.io/backup-volumes: data
    podannotations:
      backup.velero.io/backup-volumes: config
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.8.0
        workingDir: "/config"
        args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
          hosts:
            - host: "hass-editor.k.lanquarden.com"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: hass-editor-cert
              hosts:
                - "hass-editor.k.lanquarden.com"
        volumeMounts:
        - name: config
          mountPath: /config
