---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: docker.io/filebrowser/filebrowser
      tag: v2.23.0
      imagePullPolicy: IfNotPresent

    env:
      TZ: Europe/Madrid
      FB_DATABASE: "/config/filebrowser.db"
      FB_ROOT: "/data"
      FB_LOG: "stdout"
      FB_NOAUTH: "true"
      FB_PORT: "8080"

    service:
      main:
        ports:
          http:
            port: &port 8080

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "files.k.lanquarden.com"
            paths:
              - path: /
        tls:
          - secretName: filebrowser-cert
            hosts:
              - *host
    
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
  
    persistence:
      config:
        enabled: true
        existingClaim: filebrowser-config
        mountPath: /config

      documents:
        enabled: true
        existingClaim: media-nfs-unsorted-pvc
        mountPath: /data/unsorted

      unsorted:
        enabled: true
        existingClaim: media-nfs-documents-pvc
        mountPath: /data/documents