---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  targetNamespace: storage
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
      version: 1.0.x
  interval: 1h0m0s
  values:
    # workaround for bug in longhorn
    # https://github.com/longhorn/longhorn/issues/1861
    csi:
      kubeletRootDir: /var/lib/kubelet
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      host: "longhorn.k.lanquarden.com"
      tls: true
      tlsSecret: longhorn-cert

