---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-config
  namespace: network
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 10Mi

  storageClassName: rook-ceph-block
