---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work
  namespace: network
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 5G0i

  storageClassName: rook-ceph-block
