---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-data
  resources:
    requests:
      storage: 1Mi
