---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 25Gi

  storageClassName: rook-ceph-block
