---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-unsorted-pv
spec:
  storageClassName: media-nfs-unsorted
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: storone.lanquarden.com
    path: /unsorted
  mountOptions:
  - nfsvers=4.1
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-unsorted-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-nfs-unsorted
  resources:
    requests:
      storage: 1Mi
