---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mopidy-config
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi

  storageClassName: rook-ceph-block
