---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-pvc
  namespace: home
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-media
  resources:
    requests:
      storage: 1Mi
