---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.19.1
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    configuration:
      extraEnvVars:
        TZ: "Europe/Madrid"
      # features: "EnableCSI"
      provider: aws
      backupStorageLocation:
        name: default
        bucket: velero
        config:
          region: us-east-1
          s3ForcePathStyle: true
          s3Url: http://microserver.lanquarden.com:9000
          publicUrl: http://microserver.lanquarden.com:9000
      volumeSnapshotLocation:
        name: aws
        config:
          region: us-east-1
      resticTimeout: 6h
    initContainers:
    # - name: velero-plugin-for-csi
    #   image: velero/velero-plugin-for-csi:v0.1.2
    #   imagePullPolicy: IfNotPresent
    #   volumeMounts:
    #   - mountPath: /target
    #     name: plugins
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.2.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    # snapshotsEnabled: true
    snapshotsEnabled: false
    deployRestic: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
    schedules:
      bi-daily-backup:
        schedule: "0 6,18 * * *"
        template:
          ttl: "120h"
  valuesFrom:
  - kind: Secret
    name: "velero-helm-values"
