---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-all-elasticsearch"
  namespace: network
spec:
  endpointSelector:
    matchLabels:
      app: elasticsearch-master
  ingress:
    - fromEndpoints:
      - {}
  egress:
    - toEndpoints:
      - {}

