---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whisper
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: rhasspy/wyoming-whisper
      tag: 1.0.0
      imagePullPolicy: IfNotPresent

    env:
      TZ: Europe/Madrid

    args:
      - --model
        # tiny-int8 (43 MB)
        # tiny (152 MB)
        # base-int8 (80 MB)
        # base (291 MB)
        # small-int8 (255 MB)
        # small (968 MB)
        # medium-int8 (786 MB)
        # medium (3.1 GB)
      - small
      - --language
      - en

    service:
      main:
        ports:
          http:
            enabled: false
          tcp:
            enabled: true
            port: 10300
            protocol: TCP

    persistence:
      data:
        enabled: true
        type: emptyDir