---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.4.1
    env:
      TZ: "Europe/Madrid"
    service:
      additionalServices:
        - enabled: true
          nameSuffix: bittorrent
          type: LoadBalancer
          externalIPs:
            - 192.168.1.21
          port:
            port: 50413
            name: bittorrent
            protocol: TCP
            targetPort: 6881
          externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: torrent.k.lanquarden.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: qbittorrent-cert
          hosts:
            - "torrent.k.lanquarden.com"
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
    podAnnotations:
      backup.velero.io/backup-volumes: config
    additionalVolumeMounts:
      - name: nfs-media
        mountPath: "/unsorted"
    additionalVolumes:
      - name: nfs-media
        persistentVolumeClaim:
          claimName: media-nfs-unsorted-pvc
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi
