---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ping-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://raw.githubusercontent.com/czerwonk/ping_exporter/main/dist/charts/
      chart: ping-exporter
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: ping-exporter-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: czerwonk/ping_exporter
      tag: "v0.4.8"

    service:
      type: ClusterIP
      port: 9427
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9427"

    config:
      targets:
        - 8.8.8.8
        - 10.178.0.1
        - 192.168.1.1

      dns:
        refresh: 2m15s
        nameserver: 192.168.1.1

      ping:
        interval: 2s
        timeout: 3s
        history-size: 42
        payload-size: 120 

