---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ping-exporter
  namespace: monitoring
spec:
  endpoints:
    - interval: 1m
      path: /metrics
      port: http
      scrapeTimeout: 10s
  selector:
    matchLabels:
      app.kubernetes.io/instance: ping-exporter
      app.kubernetes.io/name: ping-exporter