---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: flux-system
spec:
  targetNamespace: network
  chart:
    spec:
      chart: adguard-home
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
      version: 2.2.x
  interval: 1h0m0s
  values:
    persistence:
      config:
        enabled: true
        size: 10Mi
        storageClass: rook-ceph-block
        skipuninstall: true
      work:
        enabled: true
        size: 10Gi
        skipUninstall: true
        storageClass: rook-ceph-block
        skipuninstall: true
    timezone: "Europe/Madrid"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - "adguard.k.lanquarden.com"
      tls:
        - secretName: adguard-cert
          hosts:
          - "adguard.k.lanquarden.com"
    # Expose DNS service on fixed IP
    serviceUDP:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 192.168.1.16
