---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  targetNamespace: network
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: 1.1.0-alpha.1
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: kube-system-sealed-secrets
      namespace: kube-system
  values:
    installCRDs: true
    webhook:
      enabled: true
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53
      - --dns01-recursive-nameservers-only
    cainjector:
      replicaCount: 1
    podDnsPolicy: "None"
    podDnsConfig:
      nameservers:
        - "1.1.1.1"
        - "8.8.8.8"
---
#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt-staging
#  namespace: network
#spec:
#  acme:
#    server: https://acme-staging-v02.api.letsencrypt.org/directory
#    email: lanquarden@gmail.com
#    privateKeySecretRef:
#      name: letsencrypt-staging
#    solvers:
#    - dns01:
#        cloudflare:
#          email: lanquarden@gmail.com
#          apiKeySecretRef:
#            name: cloudflare-api-key
#            key: api-key
