---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  targetNamespace: network
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
      version: 1.9.x
  interval: 1h0m0s
  values:
    
