apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-cloudflare-ddns
  namespace: network
  labels:
    app: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - name: cloudflare-ddns
          image: "hotio/cloudflare-ddns:latest"
          imagePullPolicy: Always
          env:
            - name: CF_USER
              valueFrom:
                secretKeyRef:
                  name: cloudflare-ddns
                  key: cloudflare-ddns-user
            - name: CF_APIKEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-ddns
                  key: cloudflare-ddns-token
            - name: CF_ZONES
              valueFrom:
                secretKeyRef:
                  name: cloudflare-ddns
                  key: cloudflare-ddns-zones
            - name: CF_HOSTS
              valueFrom:
                secretKeyRef:
                  name: cloudflare-ddns
                  key: cloudflare-ddns-hosts
            - name: CF_RECORDTYPES
              value: "A;A"
            - name: DETECTION_MODE
              value: dig-google.com
            - name: LOG_LEVEL
              value: 1
            - name: SLEEP_INTERVAL
              value: 300
