---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  targetNamespace: kube-system
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 9.10.x
  interval: 1h0m0s
  values:
    nodeSelector:
      kubernetes.io/hostname: beast
    logs:
      general:
        level: INFO
      access:
        enabled: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik
  namespace: kube-system
spec:
  routes:
    - kind: Rule
      match: Host(`longhorn.k.lanquarden.com`)
      services:
        - kind: Service
          name: longhorn-frontend
          port: 80
