---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  targetNamespace: network
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
      version: 9.10.x
  interval: 1h0m0s
  values:
    logs:
      general:
        level: INFO
      access:
        enabled: true
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 192.168.1.15      
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-routes
  namespace: network
spec:
  routes:
    - kind: Rule
      match: Host(`longhorn.lanquarden.com`)
      services:
        - kind: Service
          name: longhorn-frontend
          namespace: storage
          port: 80
    - kind: Rule
      match: Host(`traefik.lanquarden.com`)
      services:
        - kind: TraefikService
          name: api@internal
    - kind: Rule
      match: Host(`grafana.lanquarden.com`)
      services:
        - kind: Service
          name: kube-prometheus-stack-grafana
          namespace: monitoring
          port: 80
    - kind: Rule
      match: Host(`prometheus.lanquarden.com`)
      services:
        - kind: Service
          name: kube-prometheus-stack-prometheus
          namespace: monitoring
          port: 9090
    - kind: Rule
      match: Host(`alert.lanquarden.com`)
      services:
        - kind: Service
          name: kube-prometheus-stack-alertmanager
          namespace: monitoring
          port: 9093
    - kind: Rule
      match: Host(`adguard.lanquarden.com`)
      services:
        - kind: Service
          name: network-adguard-adguard-home
          namespace: network
          port: 3000
