---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: flux-system
spec:
	targetNamespace: network
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jacobalberty/unifi
      tag: 6.0.41
    persistence:
      enabled: true
      size: 20Gi
      storageClass: longhorn
    timezone: "Europoe/Madird"
    runAsRoot: false
    guiService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.17
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.17
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    stunService:
      type: LoadBalancer
      loadBalancerIP:  192.168.1.17
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    discoveryService:
      type: LoadBalancer
      loadBalancerIP:  192.168.1.17
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi
    resources:
      requests:
        memory: 500Mi
        cpu: 15m
      limits:
        memory: 750Mi
