---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vikunja
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: docker.io/library/caddy
      tag: 2.5.2-alpine
      imagePullPolicy: IfNotPresent

    env:
      TZ: Europe/Madrid

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "todo.k.lanquarden.com"
            paths:
              - path: /
        tls:
          - secretName: vikunja-cert
            hosts:
              - *host
    
    additionalContainers:
      api:
        image: docker.io/vikunja/api:0.19.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: data
            mountPath: /app/vikunja/files
          - name: config
            mountPath: /app/vikunja/config.yaml
            subPath: vikunja.yaml  
      frontend:
        image: docker.io/vikunja/frontend:0.19.1
        imagePullPolicy: IfNotPresent

    persistence:
      config:
        enabled: true
        type: configMap
        name: vikunja-config

      config-caddy:
        enabled: true
        type: configMap
        name: vikunja-caddy-config
        mountPath: /etc/caddy/Caddyfile
        subPath: Caddyfile

      data:
        enabled: true
        existingClaim: vikunja-data
        mountPath: /app/vikunja/files

  valuesFrom:
    - kind: Secret
      name: "vikunja-helm-values"
      optional: false