apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex-helm-values
  namespace: flux-system
spec:
  encryptedData:
    values.yaml: AgC4nsw37Ll7KNZMZjzOwgPe2udgWvFyPN0GSkkZd+K8f17Xe62Yoj6PwsvOcqeRgvzuJKFqR81SCXzmws3bjbAxSpR4p3OP5CeNYeZGxf1tg4fFhPThbEWc6cwAHG4ONVlz/wgt/rqSFD7ZOgvX1aN9h1HuIGYpt4ZnbHu6E/mR0zxsDrNf5qCFbkjSA8PaACKBzEe2Qfw+JlV+aSSSlVpFVKUW1SFWoJRbwh907WLJ0To+VtKSwJkf9SwJL3hBnKObv+dkXFTo0tliog3KKlpqGB4CuQSS4pWjhjVyAXtEhpJ26nyKvynNZsw1DR5WX2HQqm2wc/pf2ygw006RpSHB3v3P1MWPPcr6+oIh0aBGsuBCYO6MFSw8Be2ltlHwe7njOVCCjHEj9DSLOerbvTj8R6yVMReqxFs4Dxad7Wnk4xKROYIytx0iahkufnLR9uniFBpeORV5CRVI+X7XVoSGsDP/Tfb5qvKFa60tJYsfEcL5mD/FFZWEKpn9debS56bQNg4Ul21iWS3ZKH+A5sfxARaI0tZGT4jd2A7eBqfVN5dwXntx99heip8XTUhDReCwfg7Nw7MolotSZ+05v3umv/vXSpoFpmnJHfSAf3pDaAjXVf4yuvLzfgQ6rjeyZfzgdv46lIXuhFOIeNzWRBWGRojpSk+tSqpJWnpRdzexq1mz/NEkDCccI/35xZv+/TBUWOd1GTq3ii98lnTPci6x429Sv3POhFunIwMdGGBbzarIQCq/XnElC2iWVeuAqSbeWqM5i9VNs39N/fO2k6UcBfdAfhbV8zj1uhmGAzxwoZ0EbggzFUp1rJPm6IDxbQidXgeXDLKJr61QIn0XTvP3eegutIi65CVUXcnrBiu2k2oKIj0Vv1tFy+lwwVym42QO6SliqWWfiR6Tcp543t9676DSRZCeoBIBjjx4Q3P+XcfZy43/6GVff9T05cS3tlNYTYH4fP21Cpubqb3+DcL5FjaiEgvEKYDbOSk4bkjOZEaCz41xH5e/NSyTzUYRujN3LUVQisYCTbTA8Ys3MMub/ok3mK2P/hJZ9l+IpK/elsQi1VohOvfdW6MIBpsaIROaztMMGg66L3jjzrV3WIt8GJq6mMxK2Q==
  template:
    metadata:
      creationTimestamp: null
      name: dex-helm-values
      namespace: flux-system

