apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex-helm-values
  namespace: flux-system
spec:
  encryptedData:
    values.yaml: AgAno1Q/8/aYKz3gsE8TEbml0+rczPvm0JRUuWmcH5l9D98FmkD3QJ5M5U2k+FOC0WUp7BYhSvYtW6mDUuV3ibZyOpb5+Gs3RlGaOjnaErqkRVSXQZ5o+RU/ipp1a0GCcrJkyo4y24At7+6N7HNk5Ya0oJt3PKFLFQJGABYiB+aoBWtYbyhUaWzG3xYQ6RHI/mMth3AaAmF4jrequ04Jm/UqytKV1tiNs5v3SweNlXqxRfdVKvze7nsao6mr2Jlb3s9SjrSiFFFgjqpELlGstGaUHnUJ2XHouxOOtIjQ+AMIHivaMLE9JpO4BB3q5hE1uUDA63Fy5qqgPGfe379bDTNkFLHEBLeD/ERDC/DQPVr9pA/DSICOIdmTeqgSiAgjz0kCjUcHjqz0kn7lKWRGV9MMCMgUDOxJA8075aCdHUYJfQixWLU1HiixAr/ckYCmC4P5hI1aWhyUq8ddCBCQvT7wG4pIifcQIduN/dY1tmLSEilaSzgKasC01ZRUfxCq8nUNgVeWTu9IZIBqdLUxrm3Pjf1neiwTTPZ/MtxFjBJqjWPGErp3g4Go5ozD2gvN6FmfKlrvw7t+YI8m11EMPLXrGT+P9po+Swd6kbFx4veKTUzl7JnAZGDWuDF3iMo7doUe3CYqJyFrNJ0rcj0WV0eHNn6SHcGo6e7DQB0khxfd8V9PiL/idHyjfuiOAJQ/ZpFACBMr6c+fYTAJZZqK2Zug3A5FFenqRErzomDAgJbSw3qnTdalQtuCS2bA+XSzibR8CGhKIxB0xzlIhOxFHqjbZwepOqBRqQsQ+NdzHRJ2Rd6XB+Xo6VqlJbdAMpqyUgdW6/Qrdv6RL/cs/gC4oEyQEjMydIg+Hl/gMpYJAR4XlzCT2z0XA5WWhFGTPjq3JHNtBySXqaeHMZBboOF5fKkF13e2R6Qehr/wydzjWrIPQ0Fo1mayHmKL98fgaFSVPdQ7b8NqtKLz+gRjAopGkFcTGyw5jwun7o0alHCGFH/F92U2IgK0qui5FECJ+EoPlFNQpujLWfi6YPR+i4ArzvcspdxtWv7w/D7bUWLXddFk0Y5a0godArAjEVTYf72NEQ5A929Y4u5YHY4TXcwkGSF5A0M+s7A/BzvUJYyumr7AGwBwu4P9E4wFSYI=
  template:
    metadata:
      creationTimestamp: null
      name: dex-helm-values
      namespace: flux-system

