---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: beets
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: beets
      version: 13.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: linuxserver/beets
      tag: 1.6.0
    env:
      TZ: "Europe/Madrid"
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: beets.k.lanquarden.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: beets-cert
            hosts:
              - "beets.k.lanquarden.com"
    persistence:
      config:
        enabled: true
        existingClaim: beets-config
      media:
        enabled: true
        mountPath: "/media"
        existingClaim: media-nfs-media-pvc
      unsorted:
        enabled: true
        mountPath: "/unsorted"
        existingClaim: media-nfs-unsorted-pvc
    podAnnotations:
      backup.velero.io/backup-volumes: config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
