---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: beets
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: ghcr.io/lanquarden/beets
      tag: 1.6.0@sha256:b5d2eefd22170c0faca87e04cda72bc94b2d5d44c7dd3c44d20ec94959980f6e

    service:
      main:
        ports:
          http:
            port: &port_main 8337
      cli:
        enabled: true
        ports:
          ttyd:
            enabled: true
            protocol: HTTP
            port: &port_cli 7681

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host_main "beets.k.lanquarden.com"
            paths:
              - path: /
        tls:
          - secretName: beets-cert
            hosts:
              - *host_main
      cli:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host_cli "beets-cli.k.lanquarden.com"
            paths:
              - path: /
                service:
                  name: beets-cli
                  port: *port_cli
        tls:
          - secretName: beets-cli-cert
            hosts:
              - *host_cli

    env:
      TZ: "Europe/Madrid"
      BEETSDIR: "/config/beets"
    
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000

    persistence:
      config:
        enabled: true
        existingClaim: beets-config
        mountPath: /config
      music:
        enabled: true
        existingClaim: media-nfs-media-pvc
        mountPath: /media/music
        subPath: music/
      unsorted:
        enabled: true
        existingClaim: media-nfs-unsorted-pvc
        mountPath: /unsorted/music
        subPath: music/
        
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
      limits:
        memory: 400Mi
