---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: waha
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: devlikeapro/waha
      tag: latest-2025.4.1
      imagePullPolicy: IfNotPresent

    env:
      TZ: Europe/Madrid 
      

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "waha.k.lanquarden.com"
            paths:
              - path: /
        tls:
          - secretName: n8n-cert
            hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: waha-data
        mountPath: /app/.sessions

  valuesFrom:
    - kind: Secret
      name: "waha-helm-values"
      optional: false