---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: photoprism
      version: 6.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: photoprism/photoprism
      tag: "20220121"
    env:
      PHOTOPRISM_SITE_URL: "https://photos.k.lanquarden.com"
      PHOTOPRISM_SITE_TITLE: "Home Pictures"
      PHOTOPRISM_SITE_AUTHOR: "@lanquarden"
      PHOTOPRISM_ORIGINALS_PATH: /photoprism/media/pictures/
      PHOTOPRISM_STORAGE_PATH: /photoprism/storage/
      PHOTOPRISM_IMPORT_PATH: /photoprism/unsorted/pictures/
      PHOTOPRISM_ORIGINALS_LIMIT: 5000
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: photos.k.lanquarden.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: photoprism-cert
            hosts:
              - photos.k.lanquarden.com
    persistence:
      config:
        enabled: true
        mountPath: /photoprism/storage
        existingClaim: photoprism-config
      media:
        enabled: true
        mountPath: /photoprism/media
        existingClaim: media-nfs-media-pvc
      unsorted:
        enabled: true
        mountPath: /photoprism/unsorted
        existingClaim: media-nfs-unsorted-pvc
    podAnnotations:
      backup.velero.io/backup-volumes: config
  valuesFrom:
    - kind: Secret
      name: "photoprism-helm-values"
