---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: traefik-forward-auth
      version: 1.0.8
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 10m
  values:
    authHost: "auth.k.lanquarden.com"
    cookie:
      domain: "k.lanquarden.com"
    default:
      provider: "oidc"
    providers:
      oidc:
        enabled: true
        issuerUrl: "https://dex.k.lanquarden.com"
        clientId: "forward-auth"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
      hosts:
        - host: auth.k.lanquarden.com
          paths:
            - /
      tls:
        - secretName: auth-cert
          hosts:
            - "auth.k.lanquarden.com"
    middleware:
      enabled: true
      name: forward-auth
  valuesFrom:
    - kind: Secret
      name: "traefik-forward-auth-helm-values"
