service:
  frontendurl: "https://vikunja.k.lanquarden.com"
  enableregistration: true
  timezone: "Europe/Madrid"
database:
  type: "sqlite"
  path: "./files/vikunja.db"
auth:
  local:
    enabled: true
