---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-proxy-data
  namespace: games
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi

  storageClassName: rook-ceph-block
