---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: network
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  interval: 1h0m0s
  values:
    image:
      repository: adguard/adguardhome
      tag: v0.105.2
    persistence:
      config:
        enabled: true
        existingClaim: adguard-config
        skipuninstall: true
      data:
        enabled: true
        existingClaim: adguard-work
        skipuninstall: true
    env:
      TZ: "Europe/Madrid"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: "adguard.k.lanquarden.com"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: adguard-cert
          hosts:
            - "adguard.k.lanquarden.com"
    # Expose DNS service on fixed IP
    service:
      enabled: true
      port:
        port: 3000
      additionalServices:
        - enabled: true
          type: LoadBalancer
          externalTrafficPolicy: Local
          loadBalancerIP: 192.168.1.16
          nameSuffix: dns-udp
          port:
            port: 53
            name: dns-udp
            protocol: UDP
            targetPort: 53
    podAnnotations:
      backup.velero.io/backup-volumes: config
