---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: network
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  interval: 1h0m0s
  values:
    persistence:
      config:
        enabled: true
        existingClaim: adguard-config
        skipuninstall: true
      work:
        enabled: true
        existingClaim: adguard-work
        skipUninstall: true
    timezone: "Europe/Madrid"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - "adguard.k.lanquarden.com"
      tls:
        - secretName: adguard-cert
          hosts:
            - "adguard.k.lanquarden.com"
    # Expose DNS service on fixed IP
    serviceUDP:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: 192.168.0.2
    podAnnotations:
      backup.velero.io/backup-volumes: config
