---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: network
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  interval: 10m0s
  values:
    initContainers:
      copy-configmap:
        image: busybox
        command:
          - "sh"
          - "-c"
          - |
            if [ ! -f /opt/adguardhome/conf/AdGuardHome.yaml ]; then
              mkdir -p /opt/adguardhome/conf
              cp /tmp/AdGuardHome.yaml /opt/adguardhome/conf/AdGuardHome.yaml
            fi
        volumeMounts:
          - name: adguard-home-config
            mountPath: /tmp/AdGuardHome.yaml
            subPath: AdGuardHome.yaml
          - name: config
            mountPath: /opt/adguardhome/conf
        securityContext:
          runAsUser: 0
        imagePullPolicy: IfNotPresent
    image:
      repository: adguard/adguardhome
      tag: v0.107.61
    persistence:
      config:
        enabled: true
        existingClaim: adguard-config
        skipuninstall: true
      data:
        enabled: true
        existingClaim: adguard-work
        skipuninstall: true
    env:
      TZ: "Europe/Madrid"
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: "adguard.k.lanquarden.com"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: adguard-cert
            hosts:
              - "adguard.k.lanquarden.com"
    # Expose DNS service on fixed IP
    service:
      dns-tcp:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: adguard
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.1.16
        ports:
          dns-tcp:
            enable: true
            port: 53
            protocol: TCP
            targetPort: 53
      dns-udp:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: adguard
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.1.16
        ports:
          dns-udp:
            enable: true
            port: 53
            protocol: UDP
            targetPort: 53
    podAnnotations:
      backup.velero.io/backup-volumes: config
