---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  targetNamespace: media
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
      version: 2.5.0
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.middlewares: network-nextcloud@kubernetescrd
      hosts:
        - "nextcloud.k.lanquarden.com"
      tls:
        - secretName: nextcloud-cert
          hosts:
          - "nextcloud.k.lanquarden.com"
    persistence:
      enabled: true
      storageClass: rook-ceph-block
    mariadb:
      enabled: true
      master:
        persistence:
          enabled: true
          storageClass: rook-ceph-block
      replication:
        enabled: false
    metrics:
      enabled: true
      # resources:
      #   limits:
      #     cpu: 11m
      #     memory: 83Mi
      #   requests:
      #     cpu: 11m
      #     memory: 83Mi
    nextcloud:
      host: nextcloud.k.lanquarden.com
      username: admin
      extraVolumes:
        - name: nfs-data
          persistentVolumeClaim:
            claimName: nfs-data-pvc
        - name: nfs-media
          persistentVolumeClaim:
            claimName: nfs-media-pvc
      extraVolumeMounts:
        - name: nfs-data
          mountPath: /nfs/data
        - name: nfs-media
          mountPath: /nfs/media
    internalDatabase:
      enabled: false
    # resources:
    #   limits:
    #     cpu: 23m
    #     memory: 283Mi
    #   requests:
    #     cpu: 23m
    #     memory: 283Mi
    # livenessProbe:
    #   enabled: false
    # readinessProbe:
    #   enabled: false
  valuesFrom:
  - kind: Secret
    name: "nextcloud-helm-values"
      
