---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  targetNamespace: monitoring
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 11.x
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  values:
    nodeExporter:
      serviceMonitor:
        relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
          - __meta_kubernetes_pod_node_name
          targetLabel: kubernetes_node
    kubelet:
      serviceMonitor:
        metricRelabelings:
        - action: replace
          sourceLabels:
          - node
          targetLabel: instance

    alertmanager:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - "alert-manager.k.lanquarden.com"
        tls:
          - hosts:
            - "alert-manager.k.lanquarden.com"
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: rook-ceph-block
              resources:
                requests:
                  storage: 10Gi
    grafana:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - "grafana.k.lanquarden.com"
        tls:
          - secretName: grafana-cert
            hosts:
            - "grafana.k.lanquarden.com"
      plugins:
		- natel-discrete-panel
		- pr0ps-trackmap-panel
		- grafana-piechart-panel
		- vonage-status-panel
		- grafana-worldmap-panel
		- grafana-clock-panel
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          # Ref: https://grafana.com/grafana/dashboards/2842
          ceph-cluster:
            gnetId: 2842
            revision: 14
            datasource: Prometheus
          # Ref: https://grafana.com/grafana/dashboards/5336
          ceph-osd:
            gnetId: 5336
            revision: 5
            datasource: Prometheus
          # Ref: https://grafana.com/grafana/dashboards/5342
          ceph-pools:
            gnetId: 5342
            revision: 5
            datasource: Prometheus
      additionalDataSources:
      - name: Loki
        type: loki
        access: proxy
        url: http://monitoring-loki:3100
      - name: HomeAssitant
        type: influxdb
        access: proxy
        url: http://home-assistant-influxdb:8086
		database: home_assistant
    prometheus:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - "prometheus.k.lanquarden.com"
        tls:
          - hosts:
            - "prometheus.k.lanquarden.com"
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: rook-ceph-block
              accessModes: ['ReadWriteOnce']
              resources:
                requests:
                  storage: 10Gi

