---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: longhorn-charts
  namespace: flux-system
spec:
  interval: 1h0m0s
  timeout: 1m0s
  url: https://charts.longhorn.io

