---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ping-exporter-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/czerwonk/ping_exporter/main/dist/charts/
