---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: flood
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    controllerType: deployment
    image:
      repository: jesec/flood
      tag: 4.6.1
    env:
      FLOOD_OPTION_RUNDIR: /data
      FLOOD_OPTION_AUTH: "none"
      FLOOD_OPTION_QBURL: "http://qbittorrent.media.svc.cluster.local:8080"
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: flood.k.lanquarden.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: flood-cert
            hosts:
              - "flood.k.lanquarden.com"
    persistence:
      data:
        enabled: true
        existingClaim: flood-data
    podAnnotations:
      backup.velero.io/backup-volumes: data
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
  valuesFrom:
    - kind: Secret
      name: "flood-helm-values"
