---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: obsidian-db
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: docker.io/library/couchdb
      tag: 3.2.2

    env:
      TZ: Europe/Madrid

    initContainers:
      init-config:
        image: busybox:latest@sha256:20142e89dab967c01765b0aea3be4cec3a5957cc330f061e5503ef6168ae6613
        command:
          - "sh"
          - "-c"
          - "cp /tmp/config/*.ini /default.d/; ls -lrt /default.d;"
        volumeMounts:
          - name: config
            mountPath: /tmp/config
          - name: config-storage
            mountPath: /default.d

    service:
      main:
        ports:
          http:
            port: 5984

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "obsidian-db.k.lanquarden.com"
            paths:
              - path: /
        tls:
          - secretName: obsidian-db-cert
            hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: configMap
        name: obsidian-db-config
        mountPath: "-"

      config-storage:
        enabled: true
        type: emptyDir
        mountPath: /opt/couchdb/etc/default.d

      data:
        enabled: true
        existingClaim: obsidian-db-data
        mountPath: /opt/couchdb/data

  valuesFrom:
    - kind: Secret
      name: "obsidian-db-helm-values"
      optional: false
