---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: obsidian-db
  app.kubernetes.io/instance: obsidian-db
configMapGenerator:
  - name: obsidian-db-config
    files:
      - config/config.ini
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled