---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: network
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  interval: 10m0s
  values:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 192.168.1.15-192.168.1.30
        - name: bgp
          protocol: bgp
          addresses:
            - 192.168.1.31-192.168.1.39
      peers:
        - peer-address: 192.168.1.1
          peer-asn: 64512
          my-asn: 64512
#      controller:
#        prometheus:
#          serviceMonitor:
#            enabled: true
#      speaker:
#        prometheus:
#          serviceMonitor:
#            enabled: true
#      prometheusRule:
#        enabled: true
