# This is a basic workflow to help you get started with Actions
name: renovate-helmrelease-schedule

on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

jobs:
  renovate-helmrelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Renovate Helm Releases
      uses: k8s-at-home/renovate-helm-releases@v1.0.1
      with:
        cluster-path: "./cluster"

    - name: Create pull request for HelmRelease annotations
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: helm-release-annotations
        delete-branch: true
        title: "Update HelmRelease annotations for Renovate"
        signoff: true
        committer: "lanquarden <lanquarden@users.noreply.github.com>"
        author: "lanquarden <lanquarden@users.noreply.github.com>"
        assignees: "lanquarden"
        commit-message: "Update HelmRelease annotations for Renovate"
        body: |
          Add comment annotations to HelmReleases inorder for Renovate to pick up new versions of Helm charts
        labels: renovate/helm-release-annotations
