# This is a basic workflow to help you get started with Actions
name: renovate-helmrelease-schedule

on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

jobs:
  renovate-helmrelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install yq
      run: |
        mkdir -p "${GITHUB_WORKSPACE}/bin"
        echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH
        curl -sL -o "${GITHUB_WORKSPACE}/bin/yq" "https://github.com/mikefarah/yq/releases/v4.4.1/download/yq_linux_amd64"
        chmod +x "${GITHUB_WORKSPACE}/bin/yq"
    - name: Install task
      run: |
        curl -sL https://taskfile.dev/install.sh | sh
        chmod +x ${GITHUB_WORKSPACE}/bin/task
    - name: Create HelmRelease annotations
      run: echo "$(pwd)"; echo "$GITHUB_WORKSPACE}"; echo "GITHUB_PATH"; ./hack/create-helmrelease-annotations.sh

    - name: Create pull request for HelmRelease annotations
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: helm-release-annotations
        delete-branch: true
        title: "Update HelmRelease annotations for Renovate [ci-skip]"
        signoff: true
        committer: "lanquarden <lanquarden@users.noreply.github.com>"
        author: "lanquarden <lanquarden@users.noreply.github.com>"
        assignees: "lanquarden"
        commit-message: "Update HelmRelease annotations for Renovate [ci-skip]"
        body: |
          Add comment annotations to HelmReleases inorder for Renovate to pick up new versions of Helm charts
        labels: renovate/helm-release-annotations
