---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: influxdb
      version: 4.9.14
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: "influxdb"
      tag: "2.0.7"
    service:
      type: ClusterIP
    persistence:
      enabled: true
      existingClaim: influxdb-data
    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
    startupProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10
    backup:
      enabled: true
      schedule: "0 4,16 * * *"
      s3:
        endpointUrl: http://storone.lanquarden.com
        destination: s3://backup-influxdb/
        credentialsSecret: influxdb-ceph
    backupRetention:
      enabled: true
      schedule: "0 5,17 * * *"
      daysToRetain: 5
      s3:
        endpointUrl: http://storone.lanquarden.com
        bucketName: backup-influxdb
        credentialsSecret: influxdb-ceph
    podAnnotations:
      backup.velero.io/backup-volumes: influxdb-data
